# docker-compose.yml #
version: "3.4"
services:
  app:
    image: php:alpine
    volumes:
      - "./:/app"
    working_dir: /app
    command: "php artisan serve --host=0.0.0.0 --port=8080"
    ports:
      - 8080:8080